[2025-07-19T16:40:02.297+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-19T16:40:02.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ferry_portfolio_etl.extract_data scheduled__2025-07-19T16:35:00+00:00 [queued]>
[2025-07-19T16:40:02.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ferry_portfolio_etl.extract_data scheduled__2025-07-19T16:35:00+00:00 [queued]>
[2025-07-19T16:40:02.376+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-19T16:40:02.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-07-19 16:35:00+00:00
[2025-07-19T16:40:02.419+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-19T16:40:02.418+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ferry_portfolio_etl', 'extract_data', 'scheduled__2025-07-19T16:35:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/ferry_pipeline_dag.py', '--cfg-path', '/tmp/tmpwh7y467v']
[2025-07-19T16:40:02.422+0000] {standard_task_runner.py:63} INFO - Started process 2220 to run task
[2025-07-19T16:40:02.423+0000] {standard_task_runner.py:91} INFO - Job 184: Subtask extract_data
[2025-07-19T16:40:02.465+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-19T16:40:02.632+0000] {task_command.py:426} INFO - Running <TaskInstance: ferry_portfolio_etl.extract_data scheduled__2025-07-19T16:35:00+00:00 [running]> on host 289e2533e87e
[2025-07-19T16:40:02.795+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='ferry_portfolio_etl' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T16:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T16:35:00+00:00'
[2025-07-19T16:40:02.798+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-19T16:40:02.832+0000] {extract_data.py:78} INFO - ðŸš€ Starting ferry data extraction pipeline...
[2025-07-19T16:40:18.667+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-19T16:40:18.725+0000] {process_utils.py:132} INFO - Sending 15 to group 2220. PIDs of all processes in the group: [2220]
[2025-07-19T16:40:18.730+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2220
[2025-07-19T16:40:18.734+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-19T16:40:18.739+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-19T16:40:18.785+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/ferry_portfolio_pipeline/scripts/extract_data.py", line 72, in run_extraction
    main()
  File "/opt/airflow/src/ferry_portfolio_pipeline/scripts/extract_data.py", line 79, in main
    df = get_ckan_data("toronto-island-ferry-ticket-counts")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/ferry_portfolio_pipeline/scripts/extract_data.py", line 58, in get_ckan_data
    result = requests.get(search_url, params=params).json()["result"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-19T16:40:18.870+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ferry_portfolio_etl, task_id=extract_data, run_id=scheduled__2025-07-19T16:35:00+00:00, execution_date=20250719T163500, start_date=20250719T164002, end_date=20250719T164018
[2025-07-19T16:40:19.035+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2220, status='terminated', exitcode=2, started='16:40:01') (2220) terminated with exit code 2
[2025-07-19T16:40:19.046+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-07-19T16:40:19.197+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-19T16:40:22.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
