[2025-07-18T20:14:01.863+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T20:14:01.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ferry_portfolio_etl.extract_data manual__2025-07-18T20:13:59.146940+00:00 [queued]>
[2025-07-18T20:14:01.934+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ferry_portfolio_etl.extract_data manual__2025-07-18T20:13:59.146940+00:00 [queued]>
[2025-07-18T20:14:01.935+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-18T20:14:01.955+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-07-18 20:13:59.146940+00:00
[2025-07-18T20:14:02.004+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-18T20:14:02.002+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ferry_portfolio_etl', 'extract_data', 'manual__2025-07-18T20:13:59.146940+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ferry_pipeline_dag.py', '--cfg-path', '/tmp/tmp_a1rkhdd']
[2025-07-18T20:14:02.008+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2025-07-18T20:14:02.009+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask extract_data
[2025-07-18T20:14:02.055+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-18T20:14:02.145+0000] {task_command.py:426} INFO - Running <TaskInstance: ferry_portfolio_etl.extract_data manual__2025-07-18T20:13:59.146940+00:00 [running]> on host 41c60911f097
[2025-07-18T20:14:02.287+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='ferry_portfolio_etl' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T20:13:59.146940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T20:13:59.146940+00:00'
[2025-07-18T20:14:02.289+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T20:14:02.353+0000] {extract_data.py:78} INFO - üöÄ Starting ferry data extraction pipeline...
[2025-07-18T20:14:28.619+0000] {extract_data.py:80} INFO - üìä Retrieved 100000 rows and 4 columns
[2025-07-18T20:14:28.786+0000] {extract_data.py:19} INFO - ‚úÖ Saved temporary file for DVC: artifacts/ferry_raw.csv
[2025-07-18T20:14:28.787+0000] {extract_data.py:28} INFO - ü™£ Uploading file to S3: s3://ashok-ferry-data-bucket/raw_data/raw.csv
[2025-07-18T20:14:29.575+0000] {extract_data.py:37} ERROR - ‚ùå Error uploading to S3: Unable to locate credentials
[2025-07-18T20:14:29.579+0000] {extract_data.py:98} ERROR - üö® Failed in extract_data pipeline: CustomException.__init__() missing 1 required positional argument: 'error_details'
[2025-07-18T20:14:29.589+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-18T20:14:29.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T20:14:29.612+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ferry_portfolio_etl, task_id=extract_data, run_id=manual__2025-07-18T20:13:59.146940+00:00, execution_date=20250718T201359, start_date=20250718T201401, end_date=20250718T201429
[2025-07-18T20:14:29.676+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-18T20:14:29.701+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-18T20:14:29.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
